name: flutter_blue_ultra
description: Flutter plugin for connecting and communicating with Bluetooth Low Energy devices.
version: 2.0.0
homepage: https://github.com/dotintent/flutter_blue_ultra

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  # Use caret constraints to allow compatible versions
  # This allows users to use the package with other packages that depend on these
  flutter_blue_ultra_platform_interface: ^8.0.0
  flutter_blue_ultra_android: ^8.0.0
  flutter_blue_ultra_darwin: ^8.0.0
  flutter_blue_ultra_linux: ^8.0.0
  flutter_blue_ultra_web: ^8.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_blue_ultra_android
      ios:
        default_package: flutter_blue_ultra_darwin
      linux:
        default_package: flutter_blue_ultra_linux
      macos:
        default_package: flutter_blue_ultra_darwin
      web:
        default_package: flutter_blue_ultra_web
