name: flutter_blue_ultra_linux
description: Linux implementation of the flutter_blue_ultra plugin.
version: 8.0.0
homepage: https://github.com/dotintent/flutter_blue_ultra

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  bluez: '>=0.7.8 <0.9.0'
  flutter:
    sdk: flutter
  flutter_blue_ultra_platform_interface: 7.0.0
  rxdart: '>=0.27.0 <0.29.0'

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_blue_ultra
    platforms:
      linux:
        dartPluginClass: FlutterBlueUltraLinux
